package org.apache.commons.lang3.text.translate;

/* JADX INFO: loaded from: classes2.dex */
@java.lang.Deprecated
public class EntityArrays {
    private static final java.lang.String[][] APOS_ESCAPE = null;
    private static final java.lang.String[][] APOS_UNESCAPE = null;
    private static final java.lang.String[][] BASIC_ESCAPE = null;
    private static final java.lang.String[][] BASIC_UNESCAPE = null;
    private static final java.lang.String[][] HTML40_EXTENDED_ESCAPE = null;
    private static final java.lang.String[][] HTML40_EXTENDED_UNESCAPE = null;
    private static final java.lang.String[][] ISO8859_1_ESCAPE = null;
    private static final java.lang.String[][] ISO8859_1_UNESCAPE = null;
    private static final java.lang.String[][] JAVA_CTRL_CHARS_ESCAPE = null;
    private static final java.lang.String[][] JAVA_CTRL_CHARS_UNESCAPE = null;

    static {
            r0 = 96
            java.lang.String[][] r1 = new java.lang.String[r0][]
            r2 = 2
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r4 = " "
            r5 = 0
            r3[r5] = r4
            java.lang.String r4 = "&nbsp;"
            r6 = 1
            r3[r6] = r4
            r1[r5] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r4 = "¡"
            r3[r5] = r4
            java.lang.String r4 = "&iexcl;"
            r3[r6] = r4
            r1[r6] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r4 = "¢"
            r3[r5] = r4
            java.lang.String r4 = "&cent;"
            r3[r6] = r4
            r1[r2] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r4 = "£"
            r3[r5] = r4
            java.lang.String r4 = "&pound;"
            r3[r6] = r4
            r4 = 3
            r1[r4] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r7 = "¤"
            r3[r5] = r7
            java.lang.String r7 = "&curren;"
            r3[r6] = r7
            r7 = 4
            r1[r7] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r8 = "¥"
            r3[r5] = r8
            java.lang.String r8 = "&yen;"
            r3[r6] = r8
            r8 = 5
            r1[r8] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "¦"
            r3[r5] = r9
            java.lang.String r9 = "&brvbar;"
            r3[r6] = r9
            r9 = 6
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r10 = "§"
            r3[r5] = r10
            java.lang.String r10 = "&sect;"
            r3[r6] = r10
            r10 = 7
            r1[r10] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r11 = "¨"
            r3[r5] = r11
            java.lang.String r11 = "&uml;"
            r3[r6] = r11
            r11 = 8
            r1[r11] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r12 = "©"
            r3[r5] = r12
            java.lang.String r12 = "&copy;"
            r3[r6] = r12
            r12 = 9
            r1[r12] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r13 = "ª"
            r3[r5] = r13
            java.lang.String r13 = "&ordf;"
            r3[r6] = r13
            r13 = 10
            r1[r13] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r14 = "«"
            r3[r5] = r14
            java.lang.String r14 = "&laquo;"
            r3[r6] = r14
            r14 = 11
            r1[r14] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r15 = "¬"
            r3[r5] = r15
            java.lang.String r15 = "&not;"
            r3[r6] = r15
            r15 = 12
            r1[r15] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r16 = "\u00ad"
            r3[r5] = r16
            java.lang.String r16 = "&shy;"
            r3[r6] = r16
            r16 = 13
            r1[r16] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r17 = "®"
            r3[r5] = r17
            java.lang.String r17 = "&reg;"
            r3[r6] = r17
            r17 = 14
            r1[r17] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r18 = "¯"
            r3[r5] = r18
            java.lang.String r18 = "&macr;"
            r3[r6] = r18
            r18 = 15
            r1[r18] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r19 = "°"
            r3[r5] = r19
            java.lang.String r19 = "&deg;"
            r3[r6] = r19
            r19 = 16
            r1[r19] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r20 = "±"
            r3[r5] = r20
            java.lang.String r20 = "&plusmn;"
            r3[r6] = r20
            r20 = 17
            r1[r20] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r21 = "²"
            r3[r5] = r21
            java.lang.String r21 = "&sup2;"
            r3[r6] = r21
            r21 = 18
            r1[r21] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r22 = "³"
            r3[r5] = r22
            java.lang.String r22 = "&sup3;"
            r3[r6] = r22
            r22 = 19
            r1[r22] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r23 = "´"
            r3[r5] = r23
            java.lang.String r23 = "&acute;"
            r3[r6] = r23
            r23 = 20
            r1[r23] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "µ"
            r3[r5] = r24
            java.lang.String r24 = "&micro;"
            r3[r6] = r24
            r24 = 21
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "¶"
            r3[r5] = r24
            java.lang.String r24 = "&para;"
            r3[r6] = r24
            r24 = 22
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "·"
            r3[r5] = r24
            java.lang.String r24 = "&middot;"
            r3[r6] = r24
            r24 = 23
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "¸"
            r3[r5] = r24
            java.lang.String r24 = "&cedil;"
            r3[r6] = r24
            r24 = 24
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "¹"
            r3[r5] = r24
            java.lang.String r24 = "&sup1;"
            r3[r6] = r24
            r24 = 25
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "º"
            r3[r5] = r24
            java.lang.String r24 = "&ordm;"
            r3[r6] = r24
            r24 = 26
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "»"
            r3[r5] = r24
            java.lang.String r24 = "&raquo;"
            r3[r6] = r24
            r24 = 27
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "¼"
            r3[r5] = r24
            java.lang.String r24 = "&frac14;"
            r3[r6] = r24
            r24 = 28
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "½"
            r3[r5] = r24
            java.lang.String r24 = "&frac12;"
            r3[r6] = r24
            r24 = 29
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "¾"
            r3[r5] = r24
            java.lang.String r24 = "&frac34;"
            r3[r6] = r24
            r24 = 30
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "¿"
            r3[r5] = r24
            java.lang.String r24 = "&iquest;"
            r3[r6] = r24
            r24 = 31
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "À"
            r3[r5] = r24
            java.lang.String r24 = "&Agrave;"
            r3[r6] = r24
            r24 = 32
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Á"
            r3[r5] = r24
            java.lang.String r24 = "&Aacute;"
            r3[r6] = r24
            r24 = 33
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Â"
            r3[r5] = r24
            java.lang.String r24 = "&Acirc;"
            r3[r6] = r24
            r24 = 34
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Ã"
            r3[r5] = r24
            java.lang.String r24 = "&Atilde;"
            r3[r6] = r24
            r24 = 35
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Ä"
            r3[r5] = r24
            java.lang.String r24 = "&Auml;"
            r3[r6] = r24
            r24 = 36
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Å"
            r3[r5] = r24
            java.lang.String r24 = "&Aring;"
            r3[r6] = r24
            r24 = 37
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Æ"
            r3[r5] = r24
            java.lang.String r24 = "&AElig;"
            r3[r6] = r24
            r24 = 38
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Ç"
            r3[r5] = r24
            java.lang.String r24 = "&Ccedil;"
            r3[r6] = r24
            r24 = 39
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "È"
            r3[r5] = r24
            java.lang.String r24 = "&Egrave;"
            r3[r6] = r24
            r24 = 40
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "É"
            r3[r5] = r24
            java.lang.String r24 = "&Eacute;"
            r3[r6] = r24
            r24 = 41
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Ê"
            r3[r5] = r24
            java.lang.String r24 = "&Ecirc;"
            r3[r6] = r24
            r24 = 42
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Ë"
            r3[r5] = r24
            java.lang.String r24 = "&Euml;"
            r3[r6] = r24
            r24 = 43
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Ì"
            r3[r5] = r24
            java.lang.String r24 = "&Igrave;"
            r3[r6] = r24
            r24 = 44
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Í"
            r3[r5] = r24
            java.lang.String r24 = "&Iacute;"
            r3[r6] = r24
            r24 = 45
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Î"
            r3[r5] = r24
            java.lang.String r24 = "&Icirc;"
            r3[r6] = r24
            r24 = 46
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Ï"
            r3[r5] = r24
            java.lang.String r24 = "&Iuml;"
            r3[r6] = r24
            r24 = 47
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Ð"
            r3[r5] = r24
            java.lang.String r24 = "&ETH;"
            r3[r6] = r24
            r24 = 48
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Ñ"
            r3[r5] = r24
            java.lang.String r24 = "&Ntilde;"
            r3[r6] = r24
            r24 = 49
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Ò"
            r3[r5] = r24
            java.lang.String r24 = "&Ograve;"
            r3[r6] = r24
            r24 = 50
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Ó"
            r3[r5] = r24
            java.lang.String r24 = "&Oacute;"
            r3[r6] = r24
            r24 = 51
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Ô"
            r3[r5] = r24
            java.lang.String r24 = "&Ocirc;"
            r3[r6] = r24
            r24 = 52
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Õ"
            r3[r5] = r24
            java.lang.String r24 = "&Otilde;"
            r3[r6] = r24
            r24 = 53
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Ö"
            r3[r5] = r24
            java.lang.String r24 = "&Ouml;"
            r3[r6] = r24
            r24 = 54
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "×"
            r3[r5] = r24
            java.lang.String r24 = "&times;"
            r3[r6] = r24
            r24 = 55
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Ø"
            r3[r5] = r24
            java.lang.String r24 = "&Oslash;"
            r3[r6] = r24
            r24 = 56
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Ù"
            r3[r5] = r24
            java.lang.String r24 = "&Ugrave;"
            r3[r6] = r24
            r24 = 57
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Ú"
            r3[r5] = r24
            java.lang.String r24 = "&Uacute;"
            r3[r6] = r24
            r24 = 58
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Û"
            r3[r5] = r24
            java.lang.String r24 = "&Ucirc;"
            r3[r6] = r24
            r24 = 59
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Ü"
            r3[r5] = r24
            java.lang.String r24 = "&Uuml;"
            r3[r6] = r24
            r24 = 60
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Ý"
            r3[r5] = r24
            java.lang.String r24 = "&Yacute;"
            r3[r6] = r24
            r24 = 61
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Þ"
            r3[r5] = r24
            java.lang.String r24 = "&THORN;"
            r3[r6] = r24
            r24 = 62
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "ß"
            r3[r5] = r24
            java.lang.String r24 = "&szlig;"
            r3[r6] = r24
            r24 = 63
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "à"
            r3[r5] = r24
            java.lang.String r24 = "&agrave;"
            r3[r6] = r24
            r24 = 64
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "á"
            r3[r5] = r24
            java.lang.String r24 = "&aacute;"
            r3[r6] = r24
            r24 = 65
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "â"
            r3[r5] = r24
            java.lang.String r24 = "&acirc;"
            r3[r6] = r24
            r24 = 66
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "ã"
            r3[r5] = r24
            java.lang.String r24 = "&atilde;"
            r3[r6] = r24
            r24 = 67
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "ä"
            r3[r5] = r24
            java.lang.String r24 = "&auml;"
            r3[r6] = r24
            r24 = 68
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "å"
            r3[r5] = r24
            java.lang.String r24 = "&aring;"
            r3[r6] = r24
            r24 = 69
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "æ"
            r3[r5] = r24
            java.lang.String r24 = "&aelig;"
            r3[r6] = r24
            r24 = 70
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "ç"
            r3[r5] = r24
            java.lang.String r24 = "&ccedil;"
            r3[r6] = r24
            r24 = 71
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "è"
            r3[r5] = r24
            java.lang.String r24 = "&egrave;"
            r3[r6] = r24
            r24 = 72
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "é"
            r3[r5] = r24
            java.lang.String r24 = "&eacute;"
            r3[r6] = r24
            r24 = 73
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "ê"
            r3[r5] = r24
            java.lang.String r24 = "&ecirc;"
            r3[r6] = r24
            r24 = 74
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "ë"
            r3[r5] = r24
            java.lang.String r24 = "&euml;"
            r3[r6] = r24
            r24 = 75
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "ì"
            r3[r5] = r24
            java.lang.String r24 = "&igrave;"
            r3[r6] = r24
            r24 = 76
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "í"
            r3[r5] = r24
            java.lang.String r24 = "&iacute;"
            r3[r6] = r24
            r24 = 77
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "î"
            r3[r5] = r24
            java.lang.String r24 = "&icirc;"
            r3[r6] = r24
            r24 = 78
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "ï"
            r3[r5] = r24
            java.lang.String r24 = "&iuml;"
            r3[r6] = r24
            r24 = 79
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "ð"
            r3[r5] = r24
            java.lang.String r24 = "&eth;"
            r3[r6] = r24
            r24 = 80
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "ñ"
            r3[r5] = r24
            java.lang.String r24 = "&ntilde;"
            r3[r6] = r24
            r24 = 81
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "ò"
            r3[r5] = r24
            java.lang.String r24 = "&ograve;"
            r3[r6] = r24
            r24 = 82
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "ó"
            r3[r5] = r24
            java.lang.String r24 = "&oacute;"
            r3[r6] = r24
            r24 = 83
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "ô"
            r3[r5] = r24
            java.lang.String r24 = "&ocirc;"
            r3[r6] = r24
            r24 = 84
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "õ"
            r3[r5] = r24
            java.lang.String r24 = "&otilde;"
            r3[r6] = r24
            r24 = 85
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "ö"
            r3[r5] = r24
            java.lang.String r24 = "&ouml;"
            r3[r6] = r24
            r24 = 86
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "÷"
            r3[r5] = r24
            java.lang.String r24 = "&divide;"
            r3[r6] = r24
            r24 = 87
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "ø"
            r3[r5] = r24
            java.lang.String r24 = "&oslash;"
            r3[r6] = r24
            r24 = 88
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "ù"
            r3[r5] = r24
            java.lang.String r24 = "&ugrave;"
            r3[r6] = r24
            r24 = 89
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "ú"
            r3[r5] = r24
            java.lang.String r24 = "&uacute;"
            r3[r6] = r24
            r24 = 90
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "û"
            r3[r5] = r24
            java.lang.String r24 = "&ucirc;"
            r3[r6] = r24
            r24 = 91
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "ü"
            r3[r5] = r24
            java.lang.String r24 = "&uuml;"
            r3[r6] = r24
            r24 = 92
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "ý"
            r3[r5] = r24
            java.lang.String r24 = "&yacute;"
            r3[r6] = r24
            r24 = 93
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "þ"
            r3[r5] = r24
            java.lang.String r24 = "&thorn;"
            r3[r6] = r24
            r24 = 94
            r1[r24] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "ÿ"
            r3[r5] = r24
            java.lang.String r24 = "&yuml;"
            r3[r6] = r24
            r24 = 95
            r1[r24] = r3
            org.apache.commons.lang3.text.translate.EntityArrays.ISO8859_1_ESCAPE = r1
            java.lang.String[][] r1 = invert(r1)
            org.apache.commons.lang3.text.translate.EntityArrays.ISO8859_1_UNESCAPE = r1
            r1 = 152(0x98, float:2.13E-43)
            java.lang.String[][] r1 = new java.lang.String[r1][]
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "ƒ"
            r3[r5] = r24
            java.lang.String r24 = "&fnof;"
            r3[r6] = r24
            r1[r5] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Α"
            r3[r5] = r24
            java.lang.String r24 = "&Alpha;"
            r3[r6] = r24
            r1[r6] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Β"
            r3[r5] = r24
            java.lang.String r24 = "&Beta;"
            r3[r6] = r24
            r1[r2] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Γ"
            r3[r5] = r24
            java.lang.String r24 = "&Gamma;"
            r3[r6] = r24
            r1[r4] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Δ"
            r3[r5] = r24
            java.lang.String r24 = "&Delta;"
            r3[r6] = r24
            r1[r7] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Ε"
            r3[r5] = r24
            java.lang.String r24 = "&Epsilon;"
            r3[r6] = r24
            r1[r8] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r24 = "Ζ"
            r3[r5] = r24
            java.lang.String r24 = "&Zeta;"
            r3[r6] = r24
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "Η"
            r3[r5] = r9
            java.lang.String r9 = "&Eta;"
            r3[r6] = r9
            r1[r10] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "Θ"
            r3[r5] = r9
            java.lang.String r9 = "&Theta;"
            r3[r6] = r9
            r1[r11] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "Ι"
            r3[r5] = r9
            java.lang.String r9 = "&Iota;"
            r3[r6] = r9
            r1[r12] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "Κ"
            r3[r5] = r9
            java.lang.String r9 = "&Kappa;"
            r3[r6] = r9
            r1[r13] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "Λ"
            r3[r5] = r9
            java.lang.String r9 = "&Lambda;"
            r3[r6] = r9
            r1[r14] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "Μ"
            r3[r5] = r9
            java.lang.String r9 = "&Mu;"
            r3[r6] = r9
            r1[r15] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "Ν"
            r3[r5] = r9
            java.lang.String r9 = "&Nu;"
            r3[r6] = r9
            r1[r16] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "Ξ"
            r3[r5] = r9
            java.lang.String r9 = "&Xi;"
            r3[r6] = r9
            r1[r17] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "Ο"
            r3[r5] = r9
            java.lang.String r9 = "&Omicron;"
            r3[r6] = r9
            r1[r18] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "Π"
            r3[r5] = r9
            java.lang.String r9 = "&Pi;"
            r3[r6] = r9
            r1[r19] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "Ρ"
            r3[r5] = r9
            java.lang.String r9 = "&Rho;"
            r3[r6] = r9
            r1[r20] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "Σ"
            r3[r5] = r9
            java.lang.String r9 = "&Sigma;"
            r3[r6] = r9
            r1[r21] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "Τ"
            r3[r5] = r9
            java.lang.String r9 = "&Tau;"
            r3[r6] = r9
            r1[r22] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "Υ"
            r3[r5] = r9
            java.lang.String r9 = "&Upsilon;"
            r3[r6] = r9
            r1[r23] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "Φ"
            r3[r5] = r9
            java.lang.String r9 = "&Phi;"
            r3[r6] = r9
            r9 = 21
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "Χ"
            r3[r5] = r9
            java.lang.String r9 = "&Chi;"
            r3[r6] = r9
            r9 = 22
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "Ψ"
            r3[r5] = r9
            java.lang.String r9 = "&Psi;"
            r3[r6] = r9
            r9 = 23
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "Ω"
            r3[r5] = r9
            java.lang.String r9 = "&Omega;"
            r3[r6] = r9
            r9 = 24
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "α"
            r3[r5] = r9
            java.lang.String r9 = "&alpha;"
            r3[r6] = r9
            r9 = 25
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "β"
            r3[r5] = r9
            java.lang.String r9 = "&beta;"
            r3[r6] = r9
            r9 = 26
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "γ"
            r3[r5] = r9
            java.lang.String r9 = "&gamma;"
            r3[r6] = r9
            r9 = 27
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "δ"
            r3[r5] = r9
            java.lang.String r9 = "&delta;"
            r3[r6] = r9
            r9 = 28
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "ε"
            r3[r5] = r9
            java.lang.String r9 = "&epsilon;"
            r3[r6] = r9
            r9 = 29
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "ζ"
            r3[r5] = r9
            java.lang.String r9 = "&zeta;"
            r3[r6] = r9
            r9 = 30
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "η"
            r3[r5] = r9
            java.lang.String r9 = "&eta;"
            r3[r6] = r9
            r9 = 31
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "θ"
            r3[r5] = r9
            java.lang.String r9 = "&theta;"
            r3[r6] = r9
            r9 = 32
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "ι"
            r3[r5] = r9
            java.lang.String r9 = "&iota;"
            r3[r6] = r9
            r9 = 33
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "κ"
            r3[r5] = r9
            java.lang.String r9 = "&kappa;"
            r3[r6] = r9
            r9 = 34
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "λ"
            r3[r5] = r9
            java.lang.String r9 = "&lambda;"
            r3[r6] = r9
            r9 = 35
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "μ"
            r3[r5] = r9
            java.lang.String r9 = "&mu;"
            r3[r6] = r9
            r9 = 36
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "ν"
            r3[r5] = r9
            java.lang.String r9 = "&nu;"
            r3[r6] = r9
            r9 = 37
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "ξ"
            r3[r5] = r9
            java.lang.String r9 = "&xi;"
            r3[r6] = r9
            r9 = 38
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "ο"
            r3[r5] = r9
            java.lang.String r9 = "&omicron;"
            r3[r6] = r9
            r9 = 39
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "π"
            r3[r5] = r9
            java.lang.String r9 = "&pi;"
            r3[r6] = r9
            r9 = 40
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "ρ"
            r3[r5] = r9
            java.lang.String r9 = "&rho;"
            r3[r6] = r9
            r9 = 41
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "ς"
            r3[r5] = r9
            java.lang.String r9 = "&sigmaf;"
            r3[r6] = r9
            r9 = 42
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "σ"
            r3[r5] = r9
            java.lang.String r9 = "&sigma;"
            r3[r6] = r9
            r9 = 43
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "τ"
            r3[r5] = r9
            java.lang.String r9 = "&tau;"
            r3[r6] = r9
            r9 = 44
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "υ"
            r3[r5] = r9
            java.lang.String r9 = "&upsilon;"
            r3[r6] = r9
            r9 = 45
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "φ"
            r3[r5] = r9
            java.lang.String r9 = "&phi;"
            r3[r6] = r9
            r9 = 46
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "χ"
            r3[r5] = r9
            java.lang.String r9 = "&chi;"
            r3[r6] = r9
            r9 = 47
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "ψ"
            r3[r5] = r9
            java.lang.String r9 = "&psi;"
            r3[r6] = r9
            r9 = 48
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "ω"
            r3[r5] = r9
            java.lang.String r9 = "&omega;"
            r3[r6] = r9
            r9 = 49
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "ϑ"
            r3[r5] = r9
            java.lang.String r9 = "&thetasym;"
            r3[r6] = r9
            r9 = 50
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "ϒ"
            r3[r5] = r9
            java.lang.String r9 = "&upsih;"
            r3[r6] = r9
            r9 = 51
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "ϖ"
            r3[r5] = r9
            java.lang.String r9 = "&piv;"
            r3[r6] = r9
            r9 = 52
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "•"
            r3[r5] = r9
            java.lang.String r9 = "&bull;"
            r3[r6] = r9
            r9 = 53
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "…"
            r3[r5] = r9
            java.lang.String r9 = "&hellip;"
            r3[r6] = r9
            r9 = 54
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "′"
            r3[r5] = r9
            java.lang.String r9 = "&prime;"
            r3[r6] = r9
            r9 = 55
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "″"
            r3[r5] = r9
            java.lang.String r9 = "&Prime;"
            r3[r6] = r9
            r9 = 56
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "‾"
            r3[r5] = r9
            java.lang.String r9 = "&oline;"
            r3[r6] = r9
            r9 = 57
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "⁄"
            r3[r5] = r9
            java.lang.String r9 = "&frasl;"
            r3[r6] = r9
            r9 = 58
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "℘"
            r3[r5] = r9
            java.lang.String r9 = "&weierp;"
            r3[r6] = r9
            r9 = 59
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "ℑ"
            r3[r5] = r9
            java.lang.String r9 = "&image;"
            r3[r6] = r9
            r9 = 60
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "ℜ"
            r3[r5] = r9
            java.lang.String r9 = "&real;"
            r3[r6] = r9
            r9 = 61
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "™"
            r3[r5] = r9
            java.lang.String r9 = "&trade;"
            r3[r6] = r9
            r9 = 62
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "ℵ"
            r3[r5] = r9
            java.lang.String r9 = "&alefsym;"
            r3[r6] = r9
            r9 = 63
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "←"
            r3[r5] = r9
            java.lang.String r9 = "&larr;"
            r3[r6] = r9
            r9 = 64
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "↑"
            r3[r5] = r9
            java.lang.String r9 = "&uarr;"
            r3[r6] = r9
            r9 = 65
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "→"
            r3[r5] = r9
            java.lang.String r9 = "&rarr;"
            r3[r6] = r9
            r9 = 66
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "↓"
            r3[r5] = r9
            java.lang.String r9 = "&darr;"
            r3[r6] = r9
            r9 = 67
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "↔"
            r3[r5] = r9
            java.lang.String r9 = "&harr;"
            r3[r6] = r9
            r9 = 68
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "↵"
            r3[r5] = r9
            java.lang.String r9 = "&crarr;"
            r3[r6] = r9
            r9 = 69
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "⇐"
            r3[r5] = r9
            java.lang.String r9 = "&lArr;"
            r3[r6] = r9
            r9 = 70
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "⇑"
            r3[r5] = r9
            java.lang.String r9 = "&uArr;"
            r3[r6] = r9
            r9 = 71
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "⇒"
            r3[r5] = r9
            java.lang.String r9 = "&rArr;"
            r3[r6] = r9
            r9 = 72
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "⇓"
            r3[r5] = r9
            java.lang.String r9 = "&dArr;"
            r3[r6] = r9
            r9 = 73
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "⇔"
            r3[r5] = r9
            java.lang.String r9 = "&hArr;"
            r3[r6] = r9
            r9 = 74
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "∀"
            r3[r5] = r9
            java.lang.String r9 = "&forall;"
            r3[r6] = r9
            r9 = 75
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "∂"
            r3[r5] = r9
            java.lang.String r9 = "&part;"
            r3[r6] = r9
            r9 = 76
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "∃"
            r3[r5] = r9
            java.lang.String r9 = "&exist;"
            r3[r6] = r9
            r9 = 77
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "∅"
            r3[r5] = r9
            java.lang.String r9 = "&empty;"
            r3[r6] = r9
            r9 = 78
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "∇"
            r3[r5] = r9
            java.lang.String r9 = "&nabla;"
            r3[r6] = r9
            r9 = 79
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "∈"
            r3[r5] = r9
            java.lang.String r9 = "&isin;"
            r3[r6] = r9
            r9 = 80
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "∉"
            r3[r5] = r9
            java.lang.String r9 = "&notin;"
            r3[r6] = r9
            r9 = 81
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "∋"
            r3[r5] = r9
            java.lang.String r9 = "&ni;"
            r3[r6] = r9
            r9 = 82
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "∏"
            r3[r5] = r9
            java.lang.String r9 = "&prod;"
            r3[r6] = r9
            r9 = 83
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "∑"
            r3[r5] = r9
            java.lang.String r9 = "&sum;"
            r3[r6] = r9
            r9 = 84
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "−"
            r3[r5] = r9
            java.lang.String r9 = "&minus;"
            r3[r6] = r9
            r9 = 85
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "∗"
            r3[r5] = r9
            java.lang.String r9 = "&lowast;"
            r3[r6] = r9
            r9 = 86
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "√"
            r3[r5] = r9
            java.lang.String r9 = "&radic;"
            r3[r6] = r9
            r9 = 87
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "∝"
            r3[r5] = r9
            java.lang.String r9 = "&prop;"
            r3[r6] = r9
            r9 = 88
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "∞"
            r3[r5] = r9
            java.lang.String r9 = "&infin;"
            r3[r6] = r9
            r9 = 89
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "∠"
            r3[r5] = r9
            java.lang.String r9 = "&ang;"
            r3[r6] = r9
            r9 = 90
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "∧"
            r3[r5] = r9
            java.lang.String r9 = "&and;"
            r3[r6] = r9
            r9 = 91
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "∨"
            r3[r5] = r9
            java.lang.String r9 = "&or;"
            r3[r6] = r9
            r9 = 92
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "∩"
            r3[r5] = r9
            java.lang.String r9 = "&cap;"
            r3[r6] = r9
            r9 = 93
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "∪"
            r3[r5] = r9
            java.lang.String r9 = "&cup;"
            r3[r6] = r9
            r9 = 94
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "∫"
            r3[r5] = r9
            java.lang.String r9 = "&int;"
            r3[r6] = r9
            r9 = 95
            r1[r9] = r3
            java.lang.String[] r3 = new java.lang.String[r2]
            java.lang.String r9 = "∴"
            r3[r5] = r9
            java.lang.String r9 = "&there4;"
            r3[r6] = r9
            r1[r0] = r3
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "∼"
            r0[r5] = r3
            java.lang.String r3 = "&sim;"
            r0[r6] = r3
            r3 = 97
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "≅"
            r0[r5] = r3
            java.lang.String r3 = "&cong;"
            r0[r6] = r3
            r3 = 98
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "≈"
            r0[r5] = r3
            java.lang.String r3 = "&asymp;"
            r0[r6] = r3
            r3 = 99
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "≠"
            r0[r5] = r3
            java.lang.String r3 = "&ne;"
            r0[r6] = r3
            r3 = 100
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "≡"
            r0[r5] = r3
            java.lang.String r3 = "&equiv;"
            r0[r6] = r3
            r3 = 101(0x65, float:1.42E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "≤"
            r0[r5] = r3
            java.lang.String r3 = "&le;"
            r0[r6] = r3
            r3 = 102(0x66, float:1.43E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "≥"
            r0[r5] = r3
            java.lang.String r3 = "&ge;"
            r0[r6] = r3
            r3 = 103(0x67, float:1.44E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "⊂"
            r0[r5] = r3
            java.lang.String r3 = "&sub;"
            r0[r6] = r3
            r3 = 104(0x68, float:1.46E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "⊃"
            r0[r5] = r3
            java.lang.String r3 = "&sup;"
            r0[r6] = r3
            r3 = 105(0x69, float:1.47E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "⊄"
            r0[r5] = r3
            java.lang.String r3 = "&nsub;"
            r0[r6] = r3
            r3 = 106(0x6a, float:1.49E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "⊆"
            r0[r5] = r3
            java.lang.String r3 = "&sube;"
            r0[r6] = r3
            r3 = 107(0x6b, float:1.5E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "⊇"
            r0[r5] = r3
            java.lang.String r3 = "&supe;"
            r0[r6] = r3
            r3 = 108(0x6c, float:1.51E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "⊕"
            r0[r5] = r3
            java.lang.String r3 = "&oplus;"
            r0[r6] = r3
            r3 = 109(0x6d, float:1.53E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "⊗"
            r0[r5] = r3
            java.lang.String r3 = "&otimes;"
            r0[r6] = r3
            r3 = 110(0x6e, float:1.54E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "⊥"
            r0[r5] = r3
            java.lang.String r3 = "&perp;"
            r0[r6] = r3
            r3 = 111(0x6f, float:1.56E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "⋅"
            r0[r5] = r3
            java.lang.String r3 = "&sdot;"
            r0[r6] = r3
            r3 = 112(0x70, float:1.57E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "⌈"
            r0[r5] = r3
            java.lang.String r3 = "&lceil;"
            r0[r6] = r3
            r3 = 113(0x71, float:1.58E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "⌉"
            r0[r5] = r3
            java.lang.String r3 = "&rceil;"
            r0[r6] = r3
            r3 = 114(0x72, float:1.6E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "⌊"
            r0[r5] = r3
            java.lang.String r3 = "&lfloor;"
            r0[r6] = r3
            r3 = 115(0x73, float:1.61E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "⌋"
            r0[r5] = r3
            java.lang.String r3 = "&rfloor;"
            r0[r6] = r3
            r3 = 116(0x74, float:1.63E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "〈"
            r0[r5] = r3
            java.lang.String r3 = "&lang;"
            r0[r6] = r3
            r3 = 117(0x75, float:1.64E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "〉"
            r0[r5] = r3
            java.lang.String r3 = "&rang;"
            r0[r6] = r3
            r3 = 118(0x76, float:1.65E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "◊"
            r0[r5] = r3
            java.lang.String r3 = "&loz;"
            r0[r6] = r3
            r3 = 119(0x77, float:1.67E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "♠"
            r0[r5] = r3
            java.lang.String r3 = "&spades;"
            r0[r6] = r3
            r3 = 120(0x78, float:1.68E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "♣"
            r0[r5] = r3
            java.lang.String r3 = "&clubs;"
            r0[r6] = r3
            r3 = 121(0x79, float:1.7E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "♥"
            r0[r5] = r3
            java.lang.String r3 = "&hearts;"
            r0[r6] = r3
            r3 = 122(0x7a, float:1.71E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "♦"
            r0[r5] = r3
            java.lang.String r3 = "&diams;"
            r0[r6] = r3
            r3 = 123(0x7b, float:1.72E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "Œ"
            r0[r5] = r3
            java.lang.String r3 = "&OElig;"
            r0[r6] = r3
            r3 = 124(0x7c, float:1.74E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "œ"
            r0[r5] = r3
            java.lang.String r3 = "&oelig;"
            r0[r6] = r3
            r3 = 125(0x7d, float:1.75E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "Š"
            r0[r5] = r3
            java.lang.String r3 = "&Scaron;"
            r0[r6] = r3
            r3 = 126(0x7e, float:1.77E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "š"
            r0[r5] = r3
            java.lang.String r3 = "&scaron;"
            r0[r6] = r3
            r3 = 127(0x7f, float:1.78E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "Ÿ"
            r0[r5] = r3
            java.lang.String r3 = "&Yuml;"
            r0[r6] = r3
            r3 = 128(0x80, float:1.8E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "ˆ"
            r0[r5] = r3
            java.lang.String r3 = "&circ;"
            r0[r6] = r3
            r3 = 129(0x81, float:1.81E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "˜"
            r0[r5] = r3
            java.lang.String r3 = "&tilde;"
            r0[r6] = r3
            r3 = 130(0x82, float:1.82E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "\u2002"
            r0[r5] = r3
            java.lang.String r3 = "&ensp;"
            r0[r6] = r3
            r3 = 131(0x83, float:1.84E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "\u2003"
            r0[r5] = r3
            java.lang.String r3 = "&emsp;"
            r0[r6] = r3
            r3 = 132(0x84, float:1.85E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "\u2009"
            r0[r5] = r3
            java.lang.String r3 = "&thinsp;"
            r0[r6] = r3
            r3 = 133(0x85, float:1.86E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "\u200c"
            r0[r5] = r3
            java.lang.String r3 = "&zwnj;"
            r0[r6] = r3
            r3 = 134(0x86, float:1.88E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "\u200d"
            r0[r5] = r3
            java.lang.String r3 = "&zwj;"
            r0[r6] = r3
            r3 = 135(0x87, float:1.89E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "\u200e"
            r0[r5] = r3
            java.lang.String r3 = "&lrm;"
            r0[r6] = r3
            r3 = 136(0x88, float:1.9E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "\u200f"
            r0[r5] = r3
            java.lang.String r3 = "&rlm;"
            r0[r6] = r3
            r3 = 137(0x89, float:1.92E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "–"
            r0[r5] = r3
            java.lang.String r3 = "&ndash;"
            r0[r6] = r3
            r3 = 138(0x8a, float:1.93E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "—"
            r0[r5] = r3
            java.lang.String r3 = "&mdash;"
            r0[r6] = r3
            r3 = 139(0x8b, float:1.95E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "‘"
            r0[r5] = r3
            java.lang.String r3 = "&lsquo;"
            r0[r6] = r3
            r3 = 140(0x8c, float:1.96E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "’"
            r0[r5] = r3
            java.lang.String r3 = "&rsquo;"
            r0[r6] = r3
            r3 = 141(0x8d, float:1.98E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "‚"
            r0[r5] = r3
            java.lang.String r3 = "&sbquo;"
            r0[r6] = r3
            r3 = 142(0x8e, float:1.99E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "“"
            r0[r5] = r3
            java.lang.String r3 = "&ldquo;"
            r0[r6] = r3
            r3 = 143(0x8f, float:2.0E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "”"
            r0[r5] = r3
            java.lang.String r3 = "&rdquo;"
            r0[r6] = r3
            r3 = 144(0x90, float:2.02E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "„"
            r0[r5] = r3
            java.lang.String r3 = "&bdquo;"
            r0[r6] = r3
            r3 = 145(0x91, float:2.03E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "†"
            r0[r5] = r3
            java.lang.String r3 = "&dagger;"
            r0[r6] = r3
            r3 = 146(0x92, float:2.05E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "‡"
            r0[r5] = r3
            java.lang.String r3 = "&Dagger;"
            r0[r6] = r3
            r3 = 147(0x93, float:2.06E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "‰"
            r0[r5] = r3
            java.lang.String r3 = "&permil;"
            r0[r6] = r3
            r3 = 148(0x94, float:2.07E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "‹"
            r0[r5] = r3
            java.lang.String r3 = "&lsaquo;"
            r0[r6] = r3
            r3 = 149(0x95, float:2.09E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "›"
            r0[r5] = r3
            java.lang.String r3 = "&rsaquo;"
            r0[r6] = r3
            r3 = 150(0x96, float:2.1E-43)
            r1[r3] = r0
            java.lang.String[] r0 = new java.lang.String[r2]
            java.lang.String r3 = "€"
            r0[r5] = r3
            java.lang.String r3 = "&euro;"
            r0[r6] = r3
            r3 = 151(0x97, float:2.12E-43)
            r1[r3] = r0
            org.apache.commons.lang3.text.translate.EntityArrays.HTML40_EXTENDED_ESCAPE = r1
            java.lang.String[][] r0 = invert(r1)
            org.apache.commons.lang3.text.translate.EntityArrays.HTML40_EXTENDED_UNESCAPE = r0
            java.lang.String[][] r0 = new java.lang.String[r7][]
            java.lang.String[] r1 = new java.lang.String[r2]
            java.lang.String r3 = "\""
            r1[r5] = r3
            java.lang.String r3 = "&quot;"
            r1[r6] = r3
            r0[r5] = r1
            java.lang.String[] r1 = new java.lang.String[r2]
            java.lang.String r3 = "&"
            r1[r5] = r3
            java.lang.String r3 = "&amp;"
            r1[r6] = r3
            r0[r6] = r1
            java.lang.String[] r1 = new java.lang.String[r2]
            java.lang.String r3 = "<"
            r1[r5] = r3
            java.lang.String r3 = "&lt;"
            r1[r6] = r3
            r0[r2] = r1
            java.lang.String[] r1 = new java.lang.String[r2]
            java.lang.String r3 = ">"
            r1[r5] = r3
            java.lang.String r3 = "&gt;"
            r1[r6] = r3
            r0[r4] = r1
            org.apache.commons.lang3.text.translate.EntityArrays.BASIC_ESCAPE = r0
            java.lang.String[][] r0 = invert(r0)
            org.apache.commons.lang3.text.translate.EntityArrays.BASIC_UNESCAPE = r0
            java.lang.String[][] r0 = new java.lang.String[r6][]
            java.lang.String[] r1 = new java.lang.String[r2]
            java.lang.String r3 = "'"
            r1[r5] = r3
            java.lang.String r3 = "&apos;"
            r1[r6] = r3
            r0[r5] = r1
            org.apache.commons.lang3.text.translate.EntityArrays.APOS_ESCAPE = r0
            java.lang.String[][] r0 = invert(r0)
            org.apache.commons.lang3.text.translate.EntityArrays.APOS_UNESCAPE = r0
            java.lang.String[][] r0 = new java.lang.String[r8][]
            java.lang.String[] r1 = new java.lang.String[r2]
            java.lang.String r3 = "\b"
            r1[r5] = r3
            java.lang.String r3 = "\\b"
            r1[r6] = r3
            r0[r5] = r1
            java.lang.String[] r1 = new java.lang.String[r2]
            java.lang.String r3 = "\n"
            r1[r5] = r3
            java.lang.String r3 = "\\n"
            r1[r6] = r3
            r0[r6] = r1
            java.lang.String[] r1 = new java.lang.String[r2]
            java.lang.String r3 = "\t"
            r1[r5] = r3
            java.lang.String r3 = "\\t"
            r1[r6] = r3
            r0[r2] = r1
            java.lang.String[] r1 = new java.lang.String[r2]
            java.lang.String r3 = "\f"
            r1[r5] = r3
            java.lang.String r3 = "\\f"
            r1[r6] = r3
            r0[r4] = r1
            java.lang.String[] r1 = new java.lang.String[r2]
            java.lang.String r2 = "\r"
            r1[r5] = r2
            java.lang.String r2 = "\\r"
            r1[r6] = r2
            r0[r7] = r1
            org.apache.commons.lang3.text.translate.EntityArrays.JAVA_CTRL_CHARS_ESCAPE = r0
            java.lang.String[][] r0 = invert(r0)
            org.apache.commons.lang3.text.translate.EntityArrays.JAVA_CTRL_CHARS_UNESCAPE = r0
            return
    }

    @java.lang.Deprecated
    public EntityArrays() {
            r0 = this;
            r0.<init>()
            return
    }

    public static java.lang.String[][] APOS_ESCAPE() {
            java.lang.String[][] r0 = org.apache.commons.lang3.text.translate.EntityArrays.APOS_ESCAPE
            java.lang.Object r0 = r0.clone()
            java.lang.String[][] r0 = (java.lang.String[][]) r0
            return r0
    }

    public static java.lang.String[][] APOS_UNESCAPE() {
            java.lang.String[][] r0 = org.apache.commons.lang3.text.translate.EntityArrays.APOS_UNESCAPE
            java.lang.Object r0 = r0.clone()
            java.lang.String[][] r0 = (java.lang.String[][]) r0
            return r0
    }

    public static java.lang.String[][] BASIC_ESCAPE() {
            java.lang.String[][] r0 = org.apache.commons.lang3.text.translate.EntityArrays.BASIC_ESCAPE
            java.lang.Object r0 = r0.clone()
            java.lang.String[][] r0 = (java.lang.String[][]) r0
            return r0
    }

    public static java.lang.String[][] BASIC_UNESCAPE() {
            java.lang.String[][] r0 = org.apache.commons.lang3.text.translate.EntityArrays.BASIC_UNESCAPE
            java.lang.Object r0 = r0.clone()
            java.lang.String[][] r0 = (java.lang.String[][]) r0
            return r0
    }

    public static java.lang.String[][] HTML40_EXTENDED_ESCAPE() {
            java.lang.String[][] r0 = org.apache.commons.lang3.text.translate.EntityArrays.HTML40_EXTENDED_ESCAPE
            java.lang.Object r0 = r0.clone()
            java.lang.String[][] r0 = (java.lang.String[][]) r0
            return r0
    }

    public static java.lang.String[][] HTML40_EXTENDED_UNESCAPE() {
            java.lang.String[][] r0 = org.apache.commons.lang3.text.translate.EntityArrays.HTML40_EXTENDED_UNESCAPE
            java.lang.Object r0 = r0.clone()
            java.lang.String[][] r0 = (java.lang.String[][]) r0
            return r0
    }

    public static java.lang.String[][] ISO8859_1_ESCAPE() {
            java.lang.String[][] r0 = org.apache.commons.lang3.text.translate.EntityArrays.ISO8859_1_ESCAPE
            java.lang.Object r0 = r0.clone()
            java.lang.String[][] r0 = (java.lang.String[][]) r0
            return r0
    }

    public static java.lang.String[][] ISO8859_1_UNESCAPE() {
            java.lang.String[][] r0 = org.apache.commons.lang3.text.translate.EntityArrays.ISO8859_1_UNESCAPE
            java.lang.Object r0 = r0.clone()
            java.lang.String[][] r0 = (java.lang.String[][]) r0
            return r0
    }

    public static java.lang.String[][] JAVA_CTRL_CHARS_ESCAPE() {
            java.lang.String[][] r0 = org.apache.commons.lang3.text.translate.EntityArrays.JAVA_CTRL_CHARS_ESCAPE
            java.lang.Object r0 = r0.clone()
            java.lang.String[][] r0 = (java.lang.String[][]) r0
            return r0
    }

    public static java.lang.String[][] JAVA_CTRL_CHARS_UNESCAPE() {
            java.lang.String[][] r0 = org.apache.commons.lang3.text.translate.EntityArrays.JAVA_CTRL_CHARS_UNESCAPE
            java.lang.Object r0 = r0.clone()
            java.lang.String[][] r0 = (java.lang.String[][]) r0
            return r0
    }

    public static java.lang.String[][] invert(java.lang.String[][] r6) {
            int r0 = r6.length
            r1 = 2
            int[] r2 = new int[r1]
            r3 = 1
            r2[r3] = r1
            r1 = 0
            r2[r1] = r0
            java.lang.Class<java.lang.String> r0 = java.lang.String.class
            java.lang.Object r0 = java.lang.reflect.Array.newInstance(r0, r2)
            java.lang.String[][] r0 = (java.lang.String[][]) r0
            r2 = r1
        L13:
            int r4 = r6.length
            if (r2 >= r4) goto L29
            r4 = r0[r2]
            r5 = r6[r2]
            r5 = r5[r3]
            r4[r1] = r5
            r4 = r0[r2]
            r5 = r6[r2]
            r5 = r5[r1]
            r4[r3] = r5
            int r2 = r2 + 1
            goto L13
        L29:
            return r0
    }
}
