package org.apache.commons.compress.harmony.pack200;

/* JADX INFO: loaded from: classes2.dex */
public class CanonicalCodecFamilies {
    public static org.apache.commons.compress.harmony.pack200.BHSDCodec[] deltaDoubleSignedCodecs1;
    public static org.apache.commons.compress.harmony.pack200.BHSDCodec[] deltaSignedCodecs1;
    public static org.apache.commons.compress.harmony.pack200.BHSDCodec[] deltaSignedCodecs2;
    public static org.apache.commons.compress.harmony.pack200.BHSDCodec[] deltaSignedCodecs3;
    public static org.apache.commons.compress.harmony.pack200.BHSDCodec[] deltaSignedCodecs4;
    public static org.apache.commons.compress.harmony.pack200.BHSDCodec[] deltaSignedCodecs5;
    public static org.apache.commons.compress.harmony.pack200.BHSDCodec[] deltaUnsignedCodecs1;
    public static org.apache.commons.compress.harmony.pack200.BHSDCodec[] deltaUnsignedCodecs2;
    public static org.apache.commons.compress.harmony.pack200.BHSDCodec[] deltaUnsignedCodecs3;
    public static org.apache.commons.compress.harmony.pack200.BHSDCodec[] deltaUnsignedCodecs4;
    public static org.apache.commons.compress.harmony.pack200.BHSDCodec[] deltaUnsignedCodecs5;
    public static org.apache.commons.compress.harmony.pack200.BHSDCodec[] nonDeltaDoubleSignedCodecs1;
    public static org.apache.commons.compress.harmony.pack200.BHSDCodec[] nonDeltaSignedCodecs1;
    public static org.apache.commons.compress.harmony.pack200.BHSDCodec[] nonDeltaSignedCodecs2;
    public static org.apache.commons.compress.harmony.pack200.BHSDCodec[] nonDeltaUnsignedCodecs1;
    public static org.apache.commons.compress.harmony.pack200.BHSDCodec[] nonDeltaUnsignedCodecs2;
    public static org.apache.commons.compress.harmony.pack200.BHSDCodec[] nonDeltaUnsignedCodecs3;
    public static org.apache.commons.compress.harmony.pack200.BHSDCodec[] nonDeltaUnsignedCodecs4;
    public static org.apache.commons.compress.harmony.pack200.BHSDCodec[] nonDeltaUnsignedCodecs5;

    static {
            r0 = 3
            org.apache.commons.compress.harmony.pack200.BHSDCodec[] r1 = new org.apache.commons.compress.harmony.pack200.BHSDCodec[r0]
            r2 = 5
            org.apache.commons.compress.harmony.pack200.BHSDCodec r3 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r2)
            r4 = 0
            r1[r4] = r3
            r3 = 9
            org.apache.commons.compress.harmony.pack200.BHSDCodec r5 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r3)
            r6 = 1
            r1[r6] = r5
            r5 = 13
            org.apache.commons.compress.harmony.pack200.BHSDCodec r5 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r5)
            r7 = 2
            r1[r7] = r5
            org.apache.commons.compress.harmony.pack200.CanonicalCodecFamilies.nonDeltaUnsignedCodecs1 = r1
            org.apache.commons.compress.harmony.pack200.BHSDCodec[] r1 = new org.apache.commons.compress.harmony.pack200.BHSDCodec[r2]
            r5 = 17
            org.apache.commons.compress.harmony.pack200.BHSDCodec r5 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r5)
            r1[r4] = r5
            r5 = 20
            org.apache.commons.compress.harmony.pack200.BHSDCodec r5 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r5)
            r1[r6] = r5
            r5 = 23
            org.apache.commons.compress.harmony.pack200.BHSDCodec r5 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r5)
            r1[r7] = r5
            r5 = 26
            org.apache.commons.compress.harmony.pack200.BHSDCodec r5 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r5)
            r1[r0] = r5
            r5 = 29
            org.apache.commons.compress.harmony.pack200.BHSDCodec r5 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r5)
            r8 = 4
            r1[r8] = r5
            org.apache.commons.compress.harmony.pack200.CanonicalCodecFamilies.nonDeltaUnsignedCodecs2 = r1
            org.apache.commons.compress.harmony.pack200.BHSDCodec[] r1 = new org.apache.commons.compress.harmony.pack200.BHSDCodec[r2]
            r5 = 47
            org.apache.commons.compress.harmony.pack200.BHSDCodec r5 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r5)
            r1[r4] = r5
            r5 = 48
            org.apache.commons.compress.harmony.pack200.BHSDCodec r5 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r5)
            r1[r6] = r5
            r5 = 49
            org.apache.commons.compress.harmony.pack200.BHSDCodec r5 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r5)
            r1[r7] = r5
            r5 = 50
            org.apache.commons.compress.harmony.pack200.BHSDCodec r5 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r5)
            r1[r0] = r5
            r5 = 51
            org.apache.commons.compress.harmony.pack200.BHSDCodec r5 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r5)
            r1[r8] = r5
            org.apache.commons.compress.harmony.pack200.CanonicalCodecFamilies.nonDeltaUnsignedCodecs3 = r1
            org.apache.commons.compress.harmony.pack200.BHSDCodec[] r1 = new org.apache.commons.compress.harmony.pack200.BHSDCodec[r2]
            r5 = 70
            org.apache.commons.compress.harmony.pack200.BHSDCodec r5 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r5)
            r1[r4] = r5
            r5 = 71
            org.apache.commons.compress.harmony.pack200.BHSDCodec r5 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r5)
            r1[r6] = r5
            r5 = 72
            org.apache.commons.compress.harmony.pack200.BHSDCodec r5 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r5)
            r1[r7] = r5
            r5 = 73
            org.apache.commons.compress.harmony.pack200.BHSDCodec r5 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r5)
            r1[r0] = r5
            r5 = 74
            org.apache.commons.compress.harmony.pack200.BHSDCodec r5 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r5)
            r1[r8] = r5
            org.apache.commons.compress.harmony.pack200.CanonicalCodecFamilies.nonDeltaUnsignedCodecs4 = r1
            org.apache.commons.compress.harmony.pack200.BHSDCodec[] r1 = new org.apache.commons.compress.harmony.pack200.BHSDCodec[r2]
            r5 = 93
            org.apache.commons.compress.harmony.pack200.BHSDCodec r5 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r5)
            r1[r4] = r5
            r5 = 94
            org.apache.commons.compress.harmony.pack200.BHSDCodec r5 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r5)
            r1[r6] = r5
            r5 = 95
            org.apache.commons.compress.harmony.pack200.BHSDCodec r5 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r5)
            r1[r7] = r5
            r5 = 96
            org.apache.commons.compress.harmony.pack200.BHSDCodec r5 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r5)
            r1[r0] = r5
            r5 = 97
            org.apache.commons.compress.harmony.pack200.BHSDCodec r5 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r5)
            r1[r8] = r5
            org.apache.commons.compress.harmony.pack200.CanonicalCodecFamilies.nonDeltaUnsignedCodecs5 = r1
            org.apache.commons.compress.harmony.pack200.BHSDCodec[] r1 = new org.apache.commons.compress.harmony.pack200.BHSDCodec[r8]
            org.apache.commons.compress.harmony.pack200.BHSDCodec r5 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r0)
            r1[r4] = r5
            r5 = 7
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r5)
            r1[r6] = r9
            r9 = 11
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r7] = r9
            r9 = 15
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r0] = r9
            org.apache.commons.compress.harmony.pack200.CanonicalCodecFamilies.deltaUnsignedCodecs1 = r1
            org.apache.commons.compress.harmony.pack200.BHSDCodec[] r1 = new org.apache.commons.compress.harmony.pack200.BHSDCodec[r2]
            r9 = 32
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r4] = r9
            r9 = 35
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r6] = r9
            r9 = 38
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r7] = r9
            r9 = 41
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r0] = r9
            r9 = 44
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r8] = r9
            org.apache.commons.compress.harmony.pack200.CanonicalCodecFamilies.deltaUnsignedCodecs2 = r1
            org.apache.commons.compress.harmony.pack200.BHSDCodec[] r1 = new org.apache.commons.compress.harmony.pack200.BHSDCodec[r3]
            r9 = 52
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r4] = r9
            r9 = 54
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r6] = r9
            r9 = 56
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r7] = r9
            r9 = 58
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r0] = r9
            r9 = 60
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r8] = r9
            r9 = 62
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r2] = r9
            r9 = 64
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r10 = 6
            r1[r10] = r9
            r9 = 66
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r5] = r9
            r9 = 68
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r11 = 8
            r1[r11] = r9
            org.apache.commons.compress.harmony.pack200.CanonicalCodecFamilies.deltaUnsignedCodecs3 = r1
            org.apache.commons.compress.harmony.pack200.BHSDCodec[] r1 = new org.apache.commons.compress.harmony.pack200.BHSDCodec[r3]
            r9 = 75
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r4] = r9
            r9 = 77
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r6] = r9
            r9 = 79
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r7] = r9
            r9 = 81
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r0] = r9
            r9 = 83
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r8] = r9
            r9 = 85
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r2] = r9
            r9 = 87
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r10] = r9
            r9 = 89
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r5] = r9
            r9 = 91
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r11] = r9
            org.apache.commons.compress.harmony.pack200.CanonicalCodecFamilies.deltaUnsignedCodecs4 = r1
            org.apache.commons.compress.harmony.pack200.BHSDCodec[] r1 = new org.apache.commons.compress.harmony.pack200.BHSDCodec[r3]
            r9 = 98
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r4] = r9
            r9 = 100
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r6] = r9
            r9 = 102(0x66, float:1.43E-43)
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r7] = r9
            r9 = 104(0x68, float:1.46E-43)
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r0] = r9
            r9 = 106(0x6a, float:1.49E-43)
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r8] = r9
            r9 = 108(0x6c, float:1.51E-43)
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r2] = r9
            r9 = 110(0x6e, float:1.54E-43)
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r10] = r9
            r9 = 112(0x70, float:1.57E-43)
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r5] = r9
            r9 = 114(0x72, float:1.6E-43)
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r11] = r9
            org.apache.commons.compress.harmony.pack200.CanonicalCodecFamilies.deltaUnsignedCodecs5 = r1
            org.apache.commons.compress.harmony.pack200.BHSDCodec[] r1 = new org.apache.commons.compress.harmony.pack200.BHSDCodec[r8]
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r8)
            r1[r4] = r9
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r11)
            r1[r6] = r9
            r9 = 12
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r7] = r9
            r9 = 16
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r0] = r9
            org.apache.commons.compress.harmony.pack200.CanonicalCodecFamilies.deltaSignedCodecs1 = r1
            org.apache.commons.compress.harmony.pack200.BHSDCodec[] r1 = new org.apache.commons.compress.harmony.pack200.BHSDCodec[r2]
            r9 = 33
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r4] = r9
            r9 = 36
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r6] = r9
            r9 = 39
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r7] = r9
            r9 = 42
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r0] = r9
            r9 = 45
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r8] = r9
            org.apache.commons.compress.harmony.pack200.CanonicalCodecFamilies.deltaSignedCodecs2 = r1
            org.apache.commons.compress.harmony.pack200.BHSDCodec[] r1 = new org.apache.commons.compress.harmony.pack200.BHSDCodec[r3]
            r9 = 53
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r4] = r9
            r9 = 55
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r6] = r9
            r9 = 57
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r7] = r9
            r9 = 59
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r0] = r9
            r9 = 61
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r8] = r9
            r9 = 63
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r2] = r9
            r9 = 65
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r10] = r9
            r9 = 67
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r5] = r9
            r9 = 69
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r11] = r9
            org.apache.commons.compress.harmony.pack200.CanonicalCodecFamilies.deltaSignedCodecs3 = r1
            org.apache.commons.compress.harmony.pack200.BHSDCodec[] r1 = new org.apache.commons.compress.harmony.pack200.BHSDCodec[r3]
            r9 = 76
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r4] = r9
            r9 = 78
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r6] = r9
            r9 = 80
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r7] = r9
            r9 = 82
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r0] = r9
            r9 = 84
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r8] = r9
            r9 = 86
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r2] = r9
            r9 = 88
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r10] = r9
            r9 = 90
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r5] = r9
            r9 = 92
            org.apache.commons.compress.harmony.pack200.BHSDCodec r9 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r9)
            r1[r11] = r9
            org.apache.commons.compress.harmony.pack200.CanonicalCodecFamilies.deltaSignedCodecs4 = r1
            org.apache.commons.compress.harmony.pack200.BHSDCodec[] r1 = new org.apache.commons.compress.harmony.pack200.BHSDCodec[r3]
            r3 = 99
            org.apache.commons.compress.harmony.pack200.BHSDCodec r3 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r3)
            r1[r4] = r3
            r3 = 101(0x65, float:1.42E-43)
            org.apache.commons.compress.harmony.pack200.BHSDCodec r3 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r3)
            r1[r6] = r3
            r3 = 103(0x67, float:1.44E-43)
            org.apache.commons.compress.harmony.pack200.BHSDCodec r3 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r3)
            r1[r7] = r3
            r3 = 105(0x69, float:1.47E-43)
            org.apache.commons.compress.harmony.pack200.BHSDCodec r3 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r3)
            r1[r0] = r3
            r3 = 107(0x6b, float:1.5E-43)
            org.apache.commons.compress.harmony.pack200.BHSDCodec r3 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r3)
            r1[r8] = r3
            r3 = 109(0x6d, float:1.53E-43)
            org.apache.commons.compress.harmony.pack200.BHSDCodec r3 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r3)
            r1[r2] = r3
            r3 = 111(0x6f, float:1.56E-43)
            org.apache.commons.compress.harmony.pack200.BHSDCodec r3 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r3)
            r1[r10] = r3
            r3 = 113(0x71, float:1.58E-43)
            org.apache.commons.compress.harmony.pack200.BHSDCodec r3 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r3)
            r1[r5] = r3
            r3 = 115(0x73, float:1.61E-43)
            org.apache.commons.compress.harmony.pack200.BHSDCodec r3 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r3)
            r1[r11] = r3
            org.apache.commons.compress.harmony.pack200.CanonicalCodecFamilies.deltaSignedCodecs5 = r1
            org.apache.commons.compress.harmony.pack200.BHSDCodec[] r1 = new org.apache.commons.compress.harmony.pack200.BHSDCodec[r2]
            r3 = 34
            org.apache.commons.compress.harmony.pack200.BHSDCodec r3 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r3)
            r1[r4] = r3
            r3 = 37
            org.apache.commons.compress.harmony.pack200.BHSDCodec r3 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r3)
            r1[r6] = r3
            r3 = 40
            org.apache.commons.compress.harmony.pack200.BHSDCodec r3 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r3)
            r1[r7] = r3
            r3 = 43
            org.apache.commons.compress.harmony.pack200.BHSDCodec r3 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r3)
            r1[r0] = r3
            r3 = 46
            org.apache.commons.compress.harmony.pack200.BHSDCodec r3 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r3)
            r1[r8] = r3
            org.apache.commons.compress.harmony.pack200.CanonicalCodecFamilies.deltaDoubleSignedCodecs1 = r1
            org.apache.commons.compress.harmony.pack200.BHSDCodec[] r1 = new org.apache.commons.compress.harmony.pack200.BHSDCodec[r8]
            org.apache.commons.compress.harmony.pack200.BHSDCodec r3 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r7)
            r1[r4] = r3
            org.apache.commons.compress.harmony.pack200.BHSDCodec r3 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r10)
            r1[r6] = r3
            r3 = 10
            org.apache.commons.compress.harmony.pack200.BHSDCodec r3 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r3)
            r1[r7] = r3
            r3 = 14
            org.apache.commons.compress.harmony.pack200.BHSDCodec r3 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r3)
            r1[r0] = r3
            org.apache.commons.compress.harmony.pack200.CanonicalCodecFamilies.nonDeltaSignedCodecs1 = r1
            org.apache.commons.compress.harmony.pack200.BHSDCodec[] r1 = new org.apache.commons.compress.harmony.pack200.BHSDCodec[r2]
            r3 = 18
            org.apache.commons.compress.harmony.pack200.BHSDCodec r3 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r3)
            r1[r4] = r3
            r3 = 21
            org.apache.commons.compress.harmony.pack200.BHSDCodec r3 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r3)
            r1[r6] = r3
            r3 = 24
            org.apache.commons.compress.harmony.pack200.BHSDCodec r3 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r3)
            r1[r7] = r3
            r3 = 27
            org.apache.commons.compress.harmony.pack200.BHSDCodec r3 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r3)
            r1[r0] = r3
            r3 = 30
            org.apache.commons.compress.harmony.pack200.BHSDCodec r3 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r3)
            r1[r8] = r3
            org.apache.commons.compress.harmony.pack200.CanonicalCodecFamilies.nonDeltaSignedCodecs2 = r1
            org.apache.commons.compress.harmony.pack200.BHSDCodec[] r1 = new org.apache.commons.compress.harmony.pack200.BHSDCodec[r2]
            r2 = 19
            org.apache.commons.compress.harmony.pack200.BHSDCodec r2 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r2)
            r1[r4] = r2
            r2 = 22
            org.apache.commons.compress.harmony.pack200.BHSDCodec r2 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r2)
            r1[r6] = r2
            r2 = 25
            org.apache.commons.compress.harmony.pack200.BHSDCodec r2 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r2)
            r1[r7] = r2
            r2 = 28
            org.apache.commons.compress.harmony.pack200.BHSDCodec r2 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r2)
            r1[r0] = r2
            r0 = 31
            org.apache.commons.compress.harmony.pack200.BHSDCodec r0 = org.apache.commons.compress.harmony.pack200.CodecEncoding.getCanonicalCodec(r0)
            r1[r8] = r0
            org.apache.commons.compress.harmony.pack200.CanonicalCodecFamilies.nonDeltaDoubleSignedCodecs1 = r1
            return
    }

    public CanonicalCodecFamilies() {
            r0 = this;
            r0.<init>()
            return
    }
}
