package com.github.caciocavallosilano.cacio.ctc;

/* JADX WARN: Classes with same name are omitted, all sources:
  DroidBridge.Launcher-v0.3.9.apk:assets/components/caciocavallo.zip:caciocavallo17/cacio-tta-1.19.1-SNAPSHOT.jar:com/github/caciocavallosilano/cacio/ctc/KeyStrokeMappingEN.class
  DroidBridge.Launcher-v0.3.9.apk:assets/components/caciocavallo17/cacio-tta-1.19.1-SNAPSHOT.jar:com/github/caciocavallosilano/cacio/ctc/KeyStrokeMappingEN.class
 */
/* JADX INFO: loaded from: DroidBridge.Launcher-v0.3.9.apk:assets/components/caciocavallo.zip:caciocavallo17/cacio-tta-1.19.1-SNAPSHOT.jar:com/github/caciocavallosilano/cacio/ctc/KeyStrokeMappingEN.class */
class KeyStrokeMappingEN extends com.github.caciocavallosilano.cacio.ctc.AbstractKeyStrokeMapping implements com.github.caciocavallosilano.cacio.ctc.KeyStrokeMapping {
    private java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> map;

    KeyStrokeMappingEN() {
            r5 = this;
            r0 = r5
            r0.<init>()
            r0 = r5
            r1 = r5
            java.util.Map r1 = r1.getDefaultMap()
            r0.map = r1
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 48
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 48
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 48
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 41
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 49
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 49
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 49
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 33
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 50
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 50
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 50
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 64
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 51
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 51
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 51
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 35
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 52
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 52
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 52
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 36
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 53
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 53
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 53
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 37
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 54
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 54
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 54
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 94
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 55
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 55
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 55
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 38
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 56
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 56
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 56
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 42
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 57
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 57
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 57
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 40
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 65
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 97
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 65
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 65
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 66
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 98
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 66
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 66
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 192(0xc0, float:2.69E-43)
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 96
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 192(0xc0, float:2.69E-43)
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 126(0x7e, float:1.77E-43)
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 92
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 92
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 92
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 124(0x7c, float:1.74E-43)
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 67
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 99
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 67
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 67
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 93
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 93
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 93
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 125(0x7d, float:1.75E-43)
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 44
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 44
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 44
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 60
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 68
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 100
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 68
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 68
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 69
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 101(0x65, float:1.42E-43)
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 69
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 69
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 61
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 61
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 61
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 43
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 70
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 102(0x66, float:1.43E-43)
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 70
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 70
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 71
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 103(0x67, float:1.44E-43)
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 71
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 71
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 72
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 104(0x68, float:1.46E-43)
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 72
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 72
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 73
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 105(0x69, float:1.47E-43)
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 73
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 73
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 74
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 106(0x6a, float:1.49E-43)
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 74
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 74
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 75
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 107(0x6b, float:1.5E-43)
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 75
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 75
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 76
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 108(0x6c, float:1.51E-43)
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 76
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 76
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 77
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 109(0x6d, float:1.53E-43)
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 77
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 77
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 45
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 45
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 45
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 95
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 78
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 110(0x6e, float:1.54E-43)
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 78
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 78
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 79
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 111(0x6f, float:1.56E-43)
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 79
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 79
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 91
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 91
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 91
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 123(0x7b, float:1.72E-43)
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 80
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 112(0x70, float:1.57E-43)
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 80
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 80
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 46
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 46
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 46
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 62
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 81
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 113(0x71, float:1.58E-43)
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 81
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 81
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 222(0xde, float:3.11E-43)
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 39
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 222(0xde, float:3.11E-43)
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 34
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 82
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 114(0x72, float:1.6E-43)
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 82
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 82
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 83
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 115(0x73, float:1.61E-43)
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 83
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 83
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 59
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 59
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 59
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 58
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 47
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 47
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 47
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 63
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 32
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 32
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 84
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 116(0x74, float:1.63E-43)
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 84
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 84
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 85
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 117(0x75, float:1.64E-43)
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 85
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 85
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 86
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 118(0x76, float:1.65E-43)
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 86
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 86
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 87
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 119(0x77, float:1.67E-43)
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 87
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 87
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 88
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 120(0x78, float:1.68E-43)
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 88
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 88
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 89
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 121(0x79, float:1.7E-43)
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 89
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 89
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 90
            r3 = 0
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 122(0x7a, float:1.71E-43)
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            r0 = r5
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r5
            r2 = 90
            r3 = 1
            java.awt.AWTKeyStroke r1 = r1.keyStroke(r2, r3)
            r2 = 90
            java.lang.Character r2 = java.lang.Character.valueOf(r2)
            java.lang.Object r0 = r0.put(r1, r2)
            return
    }

    @Override // com.github.caciocavallosilano.cacio.ctc.KeyStrokeMapping
    public char getKeyChar(int r5, int r6) {
            r4 = this;
            r0 = r4
            r1 = r5
            r2 = r6
            java.awt.AWTKeyStroke r0 = r0.keyStroke(r1, r2)
            r7 = r0
            r0 = r4
            java.util.Map<java.awt.AWTKeyStroke, java.lang.Character> r0 = r0.map
            r1 = r7
            java.lang.Object r0 = r0.get(r1)
            java.lang.Character r0 = (java.lang.Character) r0
            r8 = r0
            r0 = r8
            if (r0 != 0) goto L1e
            r0 = 65535(0xffff, float:9.1834E-41)
            return r0
        L1e:
            r0 = r8
            char r0 = r0.charValue()
            return r0
    }
}
